# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-06 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadlinkCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('command', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BroadlinkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('port', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('model', models.CharField(max_length=30)),
            ],
        ),
    ]
